### ISSUE TITLE
How to delete key?

### ISSUE THREAD

**Issue by adaptive** [maxgoedjen/secretive#103]
Can't figure it out.
<img width="650" alt="Screen Shot 2020-06-28 at 4 36 11 AM" src="https://user-images.githubusercontent.com/17833/85937189-0f394380-b8f9-11ea-9c1d-bb108ddb165e.png">

**Comment by maxgoedjen** [comment]
Just right click on it in the sidebar :)

**Comment by adaptive** [comment]
it is working strangely after first delete stops working.
can you simulate my issue?
using the delete and backspace keys could be another option.

**Comment by rabarar** [comment]
aside from not quite working as expected, a rename as well as delete would be nice.

**Comment by shawntax** [comment]
+1, delete is very finicky. I got the delete to show up by first toggling the hide/show next to Secret Enclave at the top of the sidebar. Not ideal 😝

(I'm on MacOS `10.15.5`, Secretive `1.0.2`)
