### ISSUE TITLE
Support for macOS Mojave

### ISSUE THREAD

**Issue by manu-chroma** [maxgoedjen/secretive#105]
Hi, are there any technical challenges to support 10.14? Thanks!

**Comment by elmcrest** [comment]
While I don't know the answer since I'm just browsing by, what I can say is that technical debt is never a good choice and mac ecosystem is known for a large user base which are always up-to-date, especially (primarily) developers which use ssh...

just by 5 cents and bye

**Comment by maxgoedjen** [comment]
Hey Manu - the app is written in SwiftUI which unfortunately requires Catalina or newer, sorry :/
