### ISSUE TITLE
Support fish shell in setup instructions

### ISSUE THREAD

**Issue by cap10morgan** [maxgoedjen/secretive#107]
It would be nice if the setup shell integration instructions had an option for fish-compatible code. If I figure it out first I'll make a PR. Thanks!

**Comment by cap10morgan** [comment]
I think the suggested code should be this:

`set -g SSH_AUTH_SOCK [path]`

**Comment by maxgoedjen** [comment]
🤔 didn't realize fish had a different config for that. Doing a bit of research to see if I can tell what shell the user is using... `ProcessInfo`  seems to always report `/bin/zsh` even if I change my shell. 🤔

**Comment by cap10morgan** [comment]
@maxgoedjen Looks like you can do this (I imagine there's an API equivalent, but this is the terminal command version): `dscl . -read /Users/wmorgan UserShell` which for me returns:
`UserShell: /usr/local/bin/fish`. Hope that helps!

**Comment by maxgoedjen** [comment]
@cap10morgan yeah that was my initial thought too, but I think any shells that the Secretive process spawns will use zsh by default. 🤔
Maybe the presence of a `.config.fish` file or something? Probably have some sandboxing issues there though.

**Comment by maxgoedjen** [comment]
(I suppose I could also just have a "what shell are you using type step" as well, maybe I'm just overthinking it :P)

**Comment by cap10morgan** [comment]
Yeah or even just show all three on the same UI. I think your bases are pretty well covered with bash, zsh, and fish. :)

You could also give a hint for how to tell which one you're running for those who may not know. Might be useful given that we're still early in a transition from bash to zsh as the default.

**Comment by jerryzj** [comment]
Hi, I found that the following steps works for me

1.  Open fish config file

```shell
> vim ~/.config/fish/config.fish
```

2. In the **config.fish**, add the following line

```
set -x SSH_AUTH_SOCK /Users/$USER/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
```

**Comment by maxgoedjen** [comment]
Duping this to #131 which I plan to include in the Big Sur update. Thanks all for the idea!

**Comment by maxgoedjen** [comment]
For reference: 
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/342665/93640500-8853ae80-f9af-11ea-8f8a-ac69734be497.png"> 🥳

**Comment by maxgoedjen** [comment]
<img width="1096" alt="Screen Shot 2020-09-19 at 11 47 56 PM" src="https://user-images.githubusercontent.com/342665/93705489-aebe3a80-fad2-11ea-9378-6a120f360c61.png">
Decided to give it another pass ;)
