### ISSUE TITLE
Opt-in to update checks at setup

### ISSUE THREAD

**Issue by bufdev** [maxgoedjen/secretive#108]
Secretive connects to api.github.com on startup via https://github.com/maxgoedjen/secretive/blob/bc25576c1f1051f87b71fa1797fca10839488ce1/Brief/Updater.swift#L77. This app checking for updates in itself is fine - you likely want to know if secretive has app updates - however for an app of this nature, I'd want to control if any network calls are made, just for peace of mind. For anyone using a network monitor, it is minorly jarring to see secretive making network calls on startup - is there any way this could be surfaced as part of the setup screen that has you install the agent and set `SSH_AUTH_SOCK`?

**Comment by maxgoedjen** [comment]
Hm this isn't a bad idea - I'm kinda torn between "letting the user possibly run an insecure version" vs surprising them with a network call. 

I definitely could see why it could be jarring. Do you think a notification that this will happen would be enough for most people in this situation?

**Comment by bufdev** [comment]
Speaking for myself, I went from "let's try this" to "hold on a minute", and then had other things to do :-) A lot of people who are interested in Secretive will be running things like Lulu, Little Snitch, etc, so this will come up more often for Secretive users than typical users.

**Comment by bufdev** [comment]
Also a loud guarantee of the form "Opting out of this update will guarantee that Secretive will make zero network calls. Opting into this update guarantee that Secretive will only make this single network call, and no other network calls." would likely go a long way as well!

**Comment by maxgoedjen** [comment]
@bufdev I'll be including this in the Big Sur update. Here's what I've got for the moment (I'm still see-sawing on letting users opt out of this – like my gut is "anyone who cares can explicitly block it with Little Snitch etc" but I'm open to feedback there 🙂)

<img width="982" alt="image" src="https://user-images.githubusercontent.com/342665/93644631-40388a00-f9b7-11ea-83ef-70022038b6c3.png">

**Comment by maxgoedjen** [comment]
I've also reconfigured the updater to not prompt on first launch before you're informed of the updater.
