### ISSUE TITLE
Did not work in github without additional steps

### ISSUE THREAD

**Issue by Ewarren7** [maxgoedjen/secretive#112]
Hey very cool app. My github did not attempt to use the new key even though `echo $SSH_AUTH_SOCK` showed value that I was told to use.

I did run `ssh-add -D` to remove my old key from memory before trying so not sure if that messed things up?

I got it working though by adding to my ssh config file
```
IdentityAgent  ssh_auth_shock_path
```
where ssh_auth_shock_path is the actual path that I had set SSH_AUTH_SOCK to .

**Comment by maxgoedjen** [comment]
👋 hey @Ewarren7 – do you have anything unusual in your SSH config (like `IdentiesOnly yes` or anything)? I know I had that on my work machine and it caused issues unless you overrode it.

**Comment by Ewarren7** [comment]
Ahh yes I do. Looking into it, I can see now why that could be a problem haha. It is there twice but specific to 2 hosts so still a little confused why a problem for github however I had also removed the `Host *` I had previously for GH bc it specified a non standard IdentityFile.
