### ISSUE TITLE
Apple Watch Auth

### ISSUE THREAD

**Issue by aaron-trout** [maxgoedjen/secretive#113]
Hi! Thanks for making this, it is super cool! I have a question on when the Apple Watch authentication should be triggered. I have a MBP with Touch Bar, the TouchID authentication works great when the lid is open. However, I regularly use the Macbook in clamshell mode with my external monitor; when in this mode, I have to type my password every time whereas I was expecting the Watch to prompt me to double click the side button (like for Apple Pay).

Questions:

1) Is this the expected behaviour?
2) Does the app have any control over which auth method gets called (TouchID/Watch/Password), or is it all down to the OS?
3) Can there be an FAQ item on this please? ❤️

Thanks!
Aaron

**Comment by maxgoedjen** [comment]
Hey @aaron-trout - yeah, this is expected if you have a watch setup to unlock your Mac. 
This is configured here: SecretKit/SecureEnclave/SecureEnclaveStore.swift

You could change this to require biometrics in particular but I expected the majority of people to want Apple Watch support.

**Comment by maxgoedjen** [comment]
So just to go through your questions in order:
1: I would expect your watch to work as an authentication method here - it has for me in testing. IME the Apple Watch stuff can be a bit flakey even for unlocking the Mac, so it's possible that's causing it. If you see it consistently after rebooting etc, please let me know.

2: More specifically, here are the options. Secretive uses userPresence: https://developer.apple.com/documentation/security/secaccesscontrolcreateflags/1392879-userpresence

3: What points do you think the FAQ item should cover? (if you have something in mind and would like to PR it, I'd welcome that too 😸)

**Comment by aaron-trout** [comment]
Thanks @maxgoedjen. In this case it was not working because I did not have "Use your Apple Watch to unlock apps and your Mac" checked in System Preferences --> Security & Privacy:

![Screenshot 2020-07-07 at 10 17 56](https://user-images.githubusercontent.com/2394679/86758208-985c2300-c03b-11ea-8e43-c0825a7aa25e.png)

After checking that box and then locking my MacBook and unlocking it again with the watch, this now works as expected:

![IMG_5333](https://user-images.githubusercontent.com/2394679/86758573-dce7be80-c03b-11ea-93c4-b578f680f2dd.PNG)

Happy to do a PR to the FAQ with these instructions, I'll try and get that done today 👍
