### ISSUE TITLE
Select which key to use?

### ISSUE THREAD

**Issue by niobos** [maxgoedjen/secretive#117]
Hi,

I'm trying to use two keys in Secretive, and somehow select which key to use. When using a "normal" SSH-agent, I can select the key to use with the `ssh -i key1` or `ssh -i key2` command line option, or (more conveniently) the `IdentityFile` option in `ssh_config`.

Is there a way to accomplish this with the Secretive SSH Agent? I.e. can I somehow select which key to use? (Note: I know that the SSH-agent will try all available keys, but when using multiple GitHub profiles for example, both keys will work. They will just give you different access)

thanks in advance,
N

**Comment by martinh2011** [comment]
Copy the public key shown on the secretive UI, store it in a file and use that as IdentityFile.

**Comment by niobos** [comment]
Thank you. I learned that IdenityFile also works with public keys!
