### ISSUE TITLE
Access Keys to Copy Into Docker Container

### ISSUE THREAD

**Issue by esduran** [maxgoedjen/secretive#119]
What paths are the public/private keys stored at? I would like to be able to copy my public key into a Docker container. Or is there an alternative to accessing keys generated by Secretive?

**Comment by maxgoedjen** [comment]
The keypairs are not stored on disk at all, but in the Secure Enclave. There is no way to extract the private key, but you can copy the public key from the main Mac app.

**Comment by esduran** [comment]
@maxgoedjen I see. Thanks for answering my question promptly.

**Comment by maxgoedjen** [comment]
Np 😉
