### ISSUE TITLE
YubiKey 5C not recognized on macOS Big Sur (dev beta 2)

### ISSUE THREAD

**Issue by cap10morgan** [maxgoedjen/secretive#124]
I realize Big Sur is still in beta, so this is more of a heads up than a "fix my problem now RAR!!!!" kind of issue report. ;)

When I insert my YubiKey 5C into my iMac running Big Sur dev beta 2, Secretive still says "No Secure Storage Available."

**Comment by maxgoedjen** [comment]
Hey @cap10morgan – I just tested with my 5Ci on Big Sur and it _seems_ okay? I'm assuming you've got a valid key setup etc
<img width="863" alt="image" src="https://user-images.githubusercontent.com/342665/87869754-f0a5f580-c956-11ea-94c4-68339049a396.png">

**Comment by cap10morgan** [comment]
@maxgoedjen Not sure. I don't see any way to set it up. I should point out this is on a computer that lacks a secure enclave. So I just see the "No Secure Storage Available" dialog with the button that opens the YubiKey website.

**Comment by maxgoedjen** [comment]
@cap10morgan you'll need to configure a key using https://www.yubico.com/products/services-software/download/yubikey-manager/ before using it in Secretive.

**Comment by cap10morgan** [comment]
@maxgoedjen Ah, OK. Is that in the docs somewhere? I looked for a step I might be missing but didn't see it.

**Comment by maxgoedjen** [comment]
Nah but there probably should be. I didn't want to go down the path of documenting all the diff key brands and their respective tools, will put a point in the favor of the "document in" column, even if only "look up the manufacturer software" or something.

**Comment by cap10morgan** [comment]
Makes sense. Maybe just something like, "Note: You will need to configure your key for PIV authentication. How you do this varies by brand." And maybe throw in a, "For YubiKeys, download and run the YubiKey Manager." (with "YubiKey Manager" linked to the download) since you shout them out elsewhere in the app and they're pretty popular.

**Comment by cap10morgan** [comment]
@maxgoedjen Progress! I can see what's already on the key now, but I don't have the "+" button in the upper right corner. Do I need to do something specific in the YubiKey Manager to allow adding new SSH keys to it via Secretive?

**Comment by maxgoedjen** [comment]
@cap10morgan make sure you set up key in your authentication slot (for now, it needs to be an ECC key, Secretive doesn't support RSA ATM).

<img width="862" alt="image" src="https://user-images.githubusercontent.com/342665/88448275-f08f7500-cdf0-11ea-86a2-e4698505df8a.png">

**Comment by maxgoedjen** [comment]
Currently Secretive is not able to modify the keys stored on your YubiKey (since the interface varies per vendor)

**Comment by cap10morgan** [comment]
Thanks @maxgoedjen, very helpful. Feel free to close this issue if you're not using it to track any docs TODOs or anything. My original "bug report" is clearly user error at this point. :)

**Comment by cmoog** [comment]
Keys generated with the yubikey-agent command don't seem to appear in secretive... to reproduce on a yubikey, first reset the PIV application, then run

```
yubikey-agent -setup
```

And the resulting PIV authentication key in 9a does not work with Secretive. My best guess is that yubikey agent passes different default configuration options than keys generated from the yubikey-manager UI, and Secretive has a compatibility issues with those options? Maybe the touch policy? It can't be the algo since that is [EC256](https://github.com/FiloSottile/yubikey-agent/blob/4be40da32b6f183482930e5457acce3b265924bf/setup.go#L140)...

**Comment by maxgoedjen** [comment]
@cmoog gonna move this to #333 to keep separate, I'll follow up there.
