### ISSUE TITLE
Use IdentityAgent configuration for VS code

### ISSUE THREAD

**Issue by OdysLam** [maxgoedjen/secretive#126]
In order to use secretive with VS code and their ssh add-on, you need to add the `IdentityAgent` configuration in the Host and point that to the secretive sock.
```
Host *
 IdentityAgent /Users/odys/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
```

Perhaps it would be beneficial to list that in the helper box, as they do with the `sekey` project, where they list 2 different methods to enable it (either export or /.ssh/config).

The GH issue in the VS code repo where I chat about this:
 https://github.com/microsoft/vscode-remote-release/issues/2671#issuecomment-671013912

**Comment by maxgoedjen** [comment]
@OdysLam hey sorry this flew under my radar! I'll get this added shortly, thanks for pointing it out!
