### ISSUE TITLE
Visual Studio Code via SSH Agent asks to unlock for "Electron"

### ISSUE THREAD

**Issue by zacwest** [maxgoedjen/secretive#148]
<img width="376" alt="image" src="https://user-images.githubusercontent.com/74188/94348911-fd009b80-fff4-11ea-90de-34780a7f1ad9.png">

It seems to grab the right app icon, could it grab the bundle's product name instead if Electron is from somewhere else?

**Comment by maxgoedjen** [comment]
Interesting, so the actual process doing the requesting is Electron I guess (that lookup happens with sysctl here https://github.com/maxgoedjen/secretive/blob/main/SecretAgentKit/SigningRequestTracer.swift#L22). I pull the icon from the plist NSApp here: https://github.com/maxgoedjen/secretive/blob/main/SecretAgent/Notifier.swift#L62
Probably no reason I couldn't just pull the app name from there instead... I'm a _little_ worried about maybe an app with a false plist name entry impersonating another app, but the sysctl option wouldn't really be much safer in that regard.

**Comment by maxgoedjen** [comment]
@zacwest I think #149 should fix. I kicked off a build here, mind testing? https://github.com/maxgoedjen/secretive/actions/runs/275961323

**Comment by zacwest** [comment]
lgtm

<img width="556" alt="Screen Shot 2020-09-27 at 22 13 00" src="https://user-images.githubusercontent.com/74188/94392941-a25b6280-010e-11eb-8948-48bafcac2a8d.png">
<img width="376" alt="Screen Shot 2020-09-27 at 22 13 03" src="https://user-images.githubusercontent.com/74188/94392944-a4252600-010e-11eb-891c-e2bdbdeccf75.png">
