### ISSUE TITLE
GnuPG agent funtionality

### ISSUE THREAD

**Issue by rejsmont** [maxgoedjen/secretive#154]
Hi,

I wondered if it would be possible to implement a [GnuPG agent](https://github.com/gpg/gnupg/tree/master/agent) functionality in addition to the ssh-agent.

I know this would be a substantial effort, but I think it could be worth it! What do you think?

R.

**Comment by maxgoedjen** [comment]
Hey @rejsmont – yeah, this is definitely something I'd like to do, but it seems suuuuuuuuuper complicated compared to SSH. |(cf #63). It's a muuuuuuch bigger protocol.

I would _love_ to have the feature, dealing with GPG is always such a nightmare. Just really a challenge, we'll see if I can figure something out :)
