### ISSUE TITLE
ssh key

### ISSUE THREAD

**Issue by lizayrider** [maxgoedjen/secretive#155]
Hello,
I've just installed secretive on my Mac.
I've add a "new secret", i've add the public key on the remote serveur but it doesn't prompt for my finger to access 👍 

Here is the result for ssh -Tv git@github.com
"
OpenSSH_8.1p1, LibreSSL 2.7.3
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 47: Applying options for *
debug1: Connecting to github.com port 22.
debug1: Connection established.
debug1: identity file /Users/philippe/.ssh/id_rsa type 0
debug1: identity file /Users/philippe/.ssh/id_rsa-cert type -1
debug1: identity file /Users/philippe/.ssh/id_dsa type -1
debug1: identity file /Users/philippe/.ssh/id_dsa-cert type -1
debug1: identity file /Users/philippe/.ssh/id_ecdsa type -1
debug1: identity file /Users/philippe/.ssh/id_ecdsa-cert type -1
debug1: identity file /Users/philippe/.ssh/id_ed25519 type -1
debug1: identity file /Users/philippe/.ssh/id_ed25519-cert type -1
debug1: identity file /Users/philippe/.ssh/id_xmss type -1
debug1: identity file /Users/philippe/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.1
debug1: Remote protocol version 2.0, remote software version babeld-2715c76c
debug1: no match: babeld-2715c76c
debug1: Authenticating to github.com:22 as 'git'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: rsa-sha2-512
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-rsa SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8
The authenticity of host 'github.com (140.82.121.4)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added 'github.com,140.82.121.4' (RSA) to the list of known hosts.
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /Users/philippe/.ssh/id_rsa RSA SHA256:WPpbvo9fwLOrjPoiCbfEUIozYQKT6kyspRbkGG9j0Ew
debug1: Will attempt key: /Users/philippe/.ssh/id_dsa 
debug1: Will attempt key: /Users/philippe/.ssh/id_ecdsa 
debug1: Will attempt key: /Users/philippe/.ssh/id_ed25519 
debug1: Will attempt key: /Users/philippe/.ssh/id_xmss 
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-dss-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp521,ecdsa-sha2-nistp384,ecdsa-sha2-nistp256,rsa-sha2-512,rsa-sha2-256,ssh-rsa,ssh-dss>
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /Users/philippe/.ssh/id_rsa RSA SHA256:WPpbvo9fwLOrjPoiCbfEUIozYQKT6kyspRbkGG9j0Ew
debug1: Authentications that can continue: publickey
debug1: Trying private key: /Users/philippe/.ssh/id_dsa
debug1: Trying private key: /Users/philippe/.ssh/id_ecdsa
debug1: Trying private key: /Users/philippe/.ssh/id_ed25519
debug1: Trying private key: /Users/philippe/.ssh/id_xmss
debug1: No more authentication methods to try.
git@github.com: Permission denied (publickey).

"

Could you please help me to fix this?
Regards
P.

**Comment by maxgoedjen** [comment]
Hey @lizayrider – can you confirm you added the line in the setup script to your rc file (.bashrc, .zshrc, etc).

**Comment by lizayrider** [comment]
Hello @maxgoedjen I didn't know that I have to add a line in the setup.
Could you please help me to find which line and where do I have to add?
Regards,
P

**Comment by maxgoedjen** [comment]
@lizayrider it's in the tutorial but it's a bit easy to overlook (much improved in the Big Sur version) – you can run the tutorial again by going to Help -> Run Setup. Basically you've just gotta tech your command line how to talk to Secretive.

**Comment by lizayrider** [comment]
@maxgoedjen So great! it works perfectly now!
Thanks a lot

**Comment by lizayrider** [comment]
@maxgoedjen thanks a lot! It works perfectly! Thank you very much

**Comment by maxgoedjen** [comment]
No prob 👍
