### ISSUE TITLE
Update icon for macOS Big Sur

### ISSUE THREAD

**Issue by FIGBERT** [maxgoedjen/secretive#157]
Hey all!

I use Secretive on a daily basis, and have been running it on the macOS Big Sur beta without issue for some time. The widespread release of Big Sur is fast approaching, and Secretive should consider updating its app icon to fit the new squircle guidelines. I've taken some time to design a potential icon update, which would look something like the following:
![Secretive](https://user-images.githubusercontent.com/16868105/98430201-d35d7a00-2060-11eb-997a-f7e1889807bb.png)
I've opened a pull request to add it to the [macOS Big Sur Icon Replacements](https://github.com/elrumo/macOS_Big_Sur_icons_replacements/pull/688) repo, and would be more than happy to do the same here. Thoughts?

**Comment by maxgoedjen** [comment]
@FIGBERT good idea! I've updated the original icon file to match your design (https://github.com/maxgoedjen/secretive/pull/158) and also added the original sketch file to make PRs like yours easier :)

Thanks for suggesting this!
