### ISSUE TITLE
Agent not restarting when updating

### ISSUE THREAD

**Issue by jerryzj** [maxgoedjen/secretive#169]
Hi,

I just installed the pre-lease version 2.0.
My OS is macOS Big Sur 11.0.1 RC2(20B28)

After I set the SSH_SOCKET and install the SecretAgent, (the SecretAgent is shown in Activity Monitor) I still see the "Secret Agent is not Running" notification in Secretive App, and the GitHub ssh test still not getting the ssh key in Secure Enclave.

**Comment by jerryzj** [comment]
The setup instruction for fish is wrong.

The provided instruction is
```
set -x SSH_AUTH_SOCK=/Users/$USER/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
```

But the right instruction should be 
```
set -x SSH_AUTH_SOCK /Users/$USER/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
```
NO "=" between variable name and real path.

**Comment by maxgoedjen** [comment]
@jerryzj thanks for letting me know! I split out the fish config issue into #170.  I'll treat this one as the canonical ticket for the agent issue. I've tried to improve that in https://github.com/maxgoedjen/secretive/pull/165 but it looks like it's not enough :/
I'll experiment with that a bit more tonight and reissue 2.0 if I can get it working better.

**Comment by jerryzj** [comment]
@maxgoedjen Ok. I just installed the latest version of macOS, so I can help you test it.

**Comment by maxgoedjen** [comment]
@jerryzj sweet :) I'll tag you on the RC if I think I've got it solved.

**Comment by maxgoedjen** [comment]
@jerryzj also in the super-short-term, if you find it's blocking you from doing something, you can manually launch the agent by opening `Secretive.app/LoginItems/SecretAgent.app`

**Comment by maxgoedjen** [comment]
@jerryzj alright, THINK I've got it. I've retagged 2.0.0 with that release, feel free to give it a go. It's working pretty consistently in my testing, LMK if you have any issues. Thanks again for raising this :)

**Comment by maxgoedjen** [comment]
Just for posterity:
A few major issues addressed in that fix:
- The "running checker" didn't update its status properly after relaunching
- The uninstall reinstall stuff seems to work better when it's deferred a runloop
- I've tweaked the "force launch" thing to work a bit better (incl delaying after killing old agent/starting new one).

**Comment by jerryzj** [comment]
Thanks!
The new version is working smoothly now, but the "Secret Agent Is Not Running" is still there😂
I found another UI problem, will open another issue.
