### ISSUE TITLE
Version 2.0 UI Problem 

### ISSUE THREAD

**Issue by jerryzj** [maxgoedjen/secretive#175]
Hi, me again

I found several UI issues.

1. When try to Create/Delete keys, the window disappears. (Re-open window can fix temporary)
2. Copy public key not working. (Re-open window can fix temporary)
3. The orange box "Secret Agent Is Not Running" still exist even if it runs well.
4. The menubar buttons are not working at all.

**Comment by maxgoedjen** [comment]
@jerryzj 👋hey! Thank for filing. Could you do me a huge favor and create new issues for each one? Helps me keep track of them while I'm fixing and making release notes 🙏.

Overall that seems.... pretty weird though. This is what I'm seeing here.
![Screen Recording 2020-11-13 at 12 12 19 AM](https://user-images.githubusercontent.com/342665/99044849-45dcc700-2545-11eb-81ea-bfb20e137d8a.gif)

**Comment by maxgoedjen** [comment]
You might also want to try updating to public Big Sur if you haven't yet (it's a very slightly different build than RC2). TBH I haven't seen the behavior you're describing on any build of Big Sur though, that's pretty weird/concerning.

**Comment by jerryzj** [comment]
I already upgrade the macOS to 20B29 this morning. Maybe I should reboot it and give it another try.
I will record a short video if problems still exist.

**Comment by maxgoedjen** [comment]
Thanks!

**Comment by jerryzj** [comment]
Unfortunately, the problem still exists.
I recorded a [short video](https://youtu.be/N71Yq6A84lw) about all the situations listed above.

**Comment by maxgoedjen** [comment]
Oh that's super weird (but helpful!). Basically the entire app is unfocused for you for some reason...

**Comment by maxgoedjen** [comment]
Not really sure what would cause this... like you could try just closing the window with that red x and opening a new one, but if not something weird is going on. Any apps with like modals up or something that could be stealing the focus?

Lemme think about it a bit 🤔🤔🤔

**Comment by jerryzj** [comment]
Close the window and open a new one can fix it, I tried.

**Comment by jerryzj** [comment]
BTW, I have the following window management apps installed.

1. [Magnet ](https://magnet.crowdcafe.com/index.html)
2. [Alt-Tab](https://github.com/lwouis/alt-tab-macos)

I tried to close Alt-Tab and the problem somehow disappeared, so I guess Alt-Tab should be responsible for it (? 
I am not quite sure about it, maybe you can install Alt-Tab and try if the same problem happens.

**Comment by maxgoedjen** [comment]
Yeah I'd be hesitant to point fingers without testing it first but I'll give that a shot tomorrow. Did they update their app for Big Sur yet? Wonder if they have a general issue with it (that's just more noticeable in this app).

**Comment by maxgoedjen** [comment]
Alt-Tab (Version 6.10.0) seeeeeems okay here? Can you confirm that's the version you've got?

**Comment by jerryzj** [comment]
I am using 6.11.0. I will downgrade it.

**Comment by jerryzj** [comment]
BTW, I opened system.log and keep seeing this message
```
com.apple.xpc.launchd[1] (com.maxgoedjen.Secretive.SecretAgent[1507]): Service exited with abnormal code: 78
```
I guess that's why I still see the orange box on Secretive window

**Comment by jerryzj** [comment]
Hi, I use the following command and fix the problem.
Everything works now :)
```
xattr -d -r -s com.apple.quarantine /Applications/Secretive.app/
```

**Comment by maxgoedjen** [comment]
jerryzj thanks for the update!

Any chance you installed using brew? Think we had one more report of that. If not I'll open a new issue.

**Comment by jerryzj** [comment]
I don't use Homebrew because [this ](https://saagarjha.com/blog/2019/04/26/thoughts-on-macos-package-managers/)

**Comment by jerryzj** [comment]
BTW, This [discussion](https://forums.docker.com/t/docker-beta-on-mac-refusing-to-execute-trust-quarantined-program-file/15389) gives me the idea, it seems that the same issue could happen on different App.

**Comment by jerryzj** [comment]
It seems that the same problem appears again.
Run the following command will fix

```shell
xattr -d -r -s com.apple.quarantine /Applications/Secretive.app/
```
