### ISSUE TITLE
Overzealous error when in the user Applications folder

### ISSUE THREAD

**Issue by ticky** [maxgoedjen/secretive#177]
Hi there, it looks like as of #77 there’s now a warning about not being in the Applications folder even if it’s within the `~/Applications` folder, which as far as I understand it, gives applications the same privileges and access but doesn’t require superuser access to copy applications there. I’ve been using Secretive from there without issue, so the warning surprised me!

I believe you may want [`.allApplicationsDirectories`](https://developer.apple.com/documentation/foundation/filemanager/searchpathdirectory/allapplicationsdirectory) instead of `.applicationDirectory` in [the `ApplicationDirectoryController`](https://github.com/maxgoedjen/secretive/blob/de2252fccbbdc8fb1895c66a5cdfad9fe5f7c155/Secretive/Controllers/ApplicationDirectoryController.swift) 👍🏼

**Comment by maxgoedjen** [comment]
@ticky I had _thought_ it'd need to be in `/Applications` and not `~/Applications`, but I'm not in the habit of doing the latter, so if you're doing that and it's working fine I'll take your word for it :) Thanks for the heads up, I'll PR that.

**Comment by maxgoedjen** [comment]
(also: just to double check: the agent seems to launch correctly on startup, etc? IIRC that was the main issue there)

**Comment by ticky** [comment]
Yep, it’s been in my `~/Applications` folder ever since I started using it, and works without issue even post-reboot. :)

**Comment by ticky** [comment]
(and to confirm, yes, I just did a reboot to double check and did an SSH using it, and it worked flawlessly)

**Comment by maxgoedjen** [comment]
Thanks for double checking 🙏
This should be in the next release (I think I'll _probably_ cut 1.1 when #190 lands)

**Comment by ticky** [comment]
Looks like this ability was changed in Big Sur, so I've had to move it to the system Applications folder. Sorry for the trouble!

**Comment by maxgoedjen** [comment]
Huh, interesting. Thanks for the followup 👍

**Comment by zupo** [comment]
Hey! I've been using Secretive for about 6 months now on Sequoia, always kept it in `~/Applications`, it works without any issues, but I do see the `Not in Applications folder` warning all the time.
