### ISSUE TITLE
Add ability to export key to ssh server

### ISSUE THREAD

**Issue by lavalleeale** [maxgoedjen/secretive#180]
I am not sure how feasible this would be, but it would be really nice if there was the ability to enter user@server to export the key

**Comment by maxgoedjen** [comment]
@lavalleeale meaning just that the key would have the `max@mac.local` type suffix? I believe this user@server bit is just a comment (ie, it can be literally anything, and that's just a convention, it does not affect the key itself), correct?

**Comment by lavalleeale** [comment]
Yes, it does not affect how the key works, just makes it easier to track

**Comment by maxgoedjen** [comment]
What would be the desired behavior? Just having the key name as secretive has it at the end? A custom user@server you set in preferences or something? J trying to feel out what advantage would be for secretive to add it vs manually adding it.

**Comment by maxgoedjen** [comment]
Like I could maybe see like secretname@secretive.yourmacname.local being useful?

**Comment by maxgoedjen** [comment]
@lavalleeale think this addresses your use case? 
<img width="1012" alt="image" src="https://user-images.githubusercontent.com/342665/100552226-a56fed80-323a-11eb-843c-60a7bb48ee38.png">

**Comment by lavalleeale** [comment]
Yeah, that looks great
