### ISSUE TITLE
Non-existent information link

### ISSUE THREAD

**Issue by deni** [maxgoedjen/secretive#187]
During setup, the link for information about automatic updates does not take one to a page that has this information.

**Comment by maxgoedjen** [comment]
Can you send a screenshot of what you see/get linked to? Just testing here it seems to work correctly (linking to https://github.com/maxgoedjen/secretive/blob/main/FAQ.md#whats-this-network-request-to-github)

**Comment by maxgoedjen** [comment]
Hey @deni, friendly bump on this – still seeing it?
