### ISSUE TITLE
Agent won't load after upgrade to 1.0.3 on Catalina - Malformed bundle

### ISSUE THREAD

**Issue by Ewarren7** [maxgoedjen/secretive#189]
After upgrade, notice it wasn't working and the app says the agent is loaded. Installing agent in app did not resolve. Reinstalling 1.0.3 did not fix. On mac os 10.15.7

Reinstalled 1.0.2 and I'm back in business so not a big deal as this release has been fine for me. 

System log shows with 1.0.3
```
Dec 14 10:31:23 Mac-Pro-Pt com.apple.xpc.launchd[1] (com.maxgoedjen.Secretive.SecretAgent[52380]): Service exited with abnormal code: 78
Dec 14 10:31:23 Mac-Pro-Pt com.apple.xpc.launchd[1] (com.maxgoedjen.Secretive.SecretAgent): Service only ran for 0 seconds. Pushing respawn out by 10 seconds.
Dec 14 10:31:33 Mac-Pro-Pt com.apple.xpc.launchd[1] (com.maxgoedjen.Secretive.SecretAgent[52382]): Could not find and/or execute program specified by service: 107: Malformed bundle: com.maxgoedjen.Secretive.SecretAgent
```

**Comment by maxgoedjen** [comment]
@Ewarren7 sorry did you mean the app says it _isn't_ loaded?
If so, the 1.x series can be a bit temperamental about launching that (well, specifically launchd can be) but I added a bunch of improvements in 2.x series if you're able to upgrade.
If not, try launching the agent manually (right click on the .app -> Show package contents -> Library -> LoginItems -> SecretAgent).

**Comment by Ewarren7** [comment]
Ah yes I meant isn't loaded. I'm still holding off on Big Sur so can't move to 2 yet. 1.0.2 has and seems to still work very reliably for me so I will just stay with that for now. 

Thanks for the great work!

**Comment by maxgoedjen** [comment]
Gotcha. Thanks :)
