### ISSUE TITLE
Use the more secure SHA256 Hashing algorithm for SSH Fingerprint information to line up with ssh and other software.

### ISSUE THREAD

**Issue by dexterp** [maxgoedjen/secretive#191]
**Problem Statement**

Secretive uses MD5 fingerprint information to indentify private and public key information.
MD5 has been proven to have insecurities/collisions and has been removed from many applications including Unix/Linux password hashing schemes and for our case GitHub and OpenSSH uses SHA256 hashes as the default fingerprint information. See https://en.wikipedia.org/wiki/MD5#Collision_vulnerabilities for information on the insecurities with MD5/Collisions. 

When running openssh in verbose/debugging mode, ssh prints the fingerprint information in SHA256 E.G.

_SSH_ 
SHA256:uCi80jfBxIrNhA2K0Lu9ZPHWna1ykGmiPrlBSnTXWl8

```bash
$ GIT_SSH_COMMAND="ssh -vvv" git pull > /dev/null 2>&1 | grep 'Server accepts key'
debug1: Server accepts key: /Users/user/.ssh/id_ecdsa_github_personal ECDSA SHA256:uCi80jfBxIrNhA2K0Lu9ZPHWna1ykGmiPrlBSnTXWl8 explicit agent
 ```

_Github_
When Logged in to
https://github.com/settings/keys

Displays
SHA256:uCi80jfBxIrNhA2K0Lu9ZPHWna1ykGmiPrlBSnTXWl8

 
 This makes it easy to identify which keys are used in authentication.
 
As secretive uses MD5 as the hashing algorithm for fingerprints, two commands need to be run to get the SSHFP information in MD5 and SHA25 in order to debug

```
# SHA256
ssh-keygen -l -f /Users/user/.ssh/id_ecdsa_github_personal 
3072 SHA256:uCi80jfBxIrNhA2K0Lu9ZPHWna1ykGmiPrlBSnTXWl8 user@localhost (RSA)

# MD5
ssh-keygen -l -E md5 -f  /Users/user/.ssh/id_ecdsa_github_personal 
3072 MD5:54:f1:ea:ab:8f:66:41:90:23:ee:8c:90:7b:d2:41:a2 user@localhost (RSA)
```

This is inconvient for the purpose of debugging as the user first needs to save the Public Key to a file then run the commands against it to get both FP hashes in order to debug which key is used.

**Feature Request/Security Issue?**

Add SHA256 FP information to the Secretive GUI as the default FP information, or display both MD5 and SHA256 FPs information to line up with other tools that use the more secure SHA256 FP information.

**Comment by maxgoedjen** [comment]
🤔 huh – I think GitHub must've _just_ changed that to SHA256, that was one of the sites I was developing against and it was MD5 prior to that...

**Comment by maxgoedjen** [comment]
From like a security POV, I think the collision resistance aspect shouldn't really matter, since it's used more for identification than any actual security-related matter. But in terms of matching the key to the one you have in GitHub etc, obviously seems to make sense to do this.

**Comment by maxgoedjen** [comment]
<img width="1144" alt="image" src="https://user-images.githubusercontent.com/342665/104856973-36be2080-58ca-11eb-9925-ae95034e2f1c.png">
Inclined to do something along these lines (except obviously with the actual SHA fingerprint instead of just the MD5 one twice ;P). Could have a preference/dropdown or something instead, but doesn't seem like there'd be a ton of benefit there tbh.
