### ISSUE TITLE
Multiple authentication check in VS Code workspaces

### ISSUE THREAD

**Issue by EppO** [maxgoedjen/secretive#193]
Hi,

I'm using Visual Studio Code extensively with workspaces (multiple git repositories in the same VS Code window), using git over ssh, and I get asked to authenticate through Touch ID multiple times (not sure it's 1 authent per git repos actually), although they're all using the same destination (gitlab in the setup below) 
Here is my ssh config:

```
Host *
  ForwardAgent yes
  ServerAliveInterval 240
  AddKeysToAgent yes
  ControlMaster auto
  ControlPath ~/.ssh/%r@%h:%p
  ControlPersist yes
  Compression yes
  IdentityAgent ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

Host mygitlab
  IdentityFile ~/.ssh/gitlab.pub
  IdentitiesOnly yes
  ForwardAgent no
  SendEnv GIT_PROTOCOL
  ProxyJump none
```

and a terminal in VS code gives this:
```shell
$ echo $SSH_AUTH_SOCK
~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
$ ll ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
Permissions    Size User  Date Modified  Name
srwxr-xr-x@       0 EppO  13 Jan 12:04   ~/Library/Containers/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
```

I use SSH multiplexing, not sure that's the issue.
I made a video of the issue: https://media.giphy.com/media/2Gfm7jOCEb2dfIkvOV/giphy.gif

**Comment by maxgoedjen** [comment]
Hmmm... unfortunately not sure there's a ton we can do on this one. The prompt comes from the system itself, not Secretive. (basically, when they key is created, we set a flag that says "prompt for access," and then the system will always ask). There MIGHT be a flag that allows like a "warm" period where it won't reprompt, but I'll have to investigate that.

**Comment by maxgoedjen** [comment]
Yeah just double checked the docs, doesn't look like there's a way
https://developer.apple.com/documentation/security/secaccesscontrolcreateflags
https://developer.apple.com/documentation/security/keychain_services/keychain_items/restricting_keychain_item_accessibility

My recommendation would be just to not have "require Touch ID" on for those keys – Secretive will still store them in the SEP and notify you when they're accessed. If you do know of a way to accomplish this though please reopen this ticket, definitely something I'd be interested in adding as an option.

**Comment by maxgoedjen** [comment]
https://github.com/maxgoedjen/secretive/blob/main/SecretKit/SecureEnclave/SecureEnclaveStore.swift#L82
For posterity, I also tried setting `touchIDAuthenticationAllowableReuseDuration` on this, but it doesn't seem to have any visible effect.

**Comment by Manouchehri** [comment]
I finally figured out the issue, it's because VS Code makes more than 10 sessions. Easy fix thankfully!

```sh
sudo sed -i 's/#MaxSessions 10/MaxSessions 128/' /etc/ssh/sshd_config
sudo systemctl reload sshd.service
```

**Comment by maxgoedjen** [comment]
Interesting, thanks for the info @Manouchehri

**Comment by ThibaultGROUEIX** [comment]
@Manouchehri, Is there a way to check the number of sessions launched by VS Code? 

I don't have sudo access to my remote server but I could ask the administrator to run these commands if I am fairly sure that's the problem.
Thanks :)

**Comment by Manouchehri** [comment]
You can check the number of sessions currently in use by running `w` or `who`.

You should probably just run your own OpenSSH server as a non-root user. https://serverfault.com/a/946877 If you can't adjust `MaxSessions`, I don't think you're going to have a good experience with multiplexing and VS Code Remote.

**Comment by maxgoedjen** [comment]
Reopening this one as the parent issue of #238 and #250.

**Comment by maxgoedjen** [comment]
Duping this out to #251, but I played around with this a little bit more today and _might_ have a path forward (although it has some security implications I need to consider and that I'll discuss in that thread).
