### ISSUE TITLE
Consider configuring ssh directly instead of setting environment variable?

### ISSUE THREAD

**Issue by ferlatte** [maxgoedjen/secretive#194]
Hey, this project is great and it has been a time saver. When I set it up, I ended up configuring ssh directly (via adding IdentityAgent to ~.ssh/config) so I didn't have to worry about editor integration or shell differences.

Is this an approach that you've found to be a problem or would a patch to suggest this approach instead of shell variables be welcome?

**Comment by maxgoedjen** [comment]
TBH if my memory is correct I mostly just chose this approach because that's what the inspiration for this project (sekey) did.... Have you been using this `~/.ssh/config` successfully?

**Comment by ferlatte** [comment]
Yeah, I have used the following config for years:

```
Host *
    IdentityAgent ~/.gnupg/S.gpg-agent.ssh
```

When I switched to Secretive, I changed it to this

```
Host *
    IdentityAgent ~/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh
```

Works great, and it means that GUI tools like EMACS and VSCode can use ssh with Secretive as well.
