### ISSUE TITLE
Updater should only suggest the latest version your OS can run

### ISSUE THREAD

**Issue by maxgoedjen** [maxgoedjen/secretive#195]

**Comment by l2dy** [comment]
Was this cherry-picked to the 1.0.x branch? Version 1.0.3 still generates update notifications for 2.x on Catalina.

**Comment by maxgoedjen** [comment]
@l2dy it was not – I fixed the ability to ignore updates in that branch, but this change landed after that (and is mostly intended as a forward looking thing).
