### ISSUE TITLE
Improve wording around auth requirements during secret creation

### ISSUE THREAD

**Issue by joshheyse** [maxgoedjen/secretive#209]
Currently every time I run a command which requires the ssh key singing I am prompted to type in my password or auth using my watch.  This is fine for most things, but really inconvenient when working with git.  

It would be great if there was a way to be able to reuse the auth session for say 60 minutes for a certain key.

**Comment by joshheyse** [comment]
After digging around in the code, I realized that If you uncheck the "Requires authentication (Biometrics or Password)" you will not be prompted for auth every time.

Based on the code, the key is only accessible when the device is unlocked by the user if this is unchecked.  So the feature is already there, but the label could be clearer.

Maybe a pair of radio buttons (instead of a checkbox)?
- Requires authentication (Biometrics or Password) for use each time
- Does not require authentication for each use once the computer is unlocked by the user

Thanks for your hard work on the project!

**Comment by maxgoedjen** [comment]
Hm yeah I like that, does feel a bit clearer. 
I'll put it on the docket (PR's happily accepted too though, if you're up for it)

**Comment by joshheyse** [comment]
It should be pretty easy to do.  I've never worked on a swift app, so this would be fun.  Just have to get an env set up for it.

**Comment by maxgoedjen** [comment]
@joshheyse think really the only setup step needed should be changing bundle IDs so you can sign it, otherwise should be pretty much clone-and-go. The file you'll need to work in is here: https://github.com/maxgoedjen/secretive/blob/main/Secretive/Views/CreateSecretView.swift
If you run into any issues or anything, ping me here and I'll try and help :)

**Comment by joshheyse** [comment]
@maxgoedjen That was pretty easy once I figured out what magic buttons and selections were necessary to sign the app for development.
