### ISSUE TITLE
Secretive management UI doesn't display secrets on macOS 12.0 Monterrey (beta 3)

### ISSUE THREAD

**Issue by maxgoedjen** [maxgoedjen/secretive#225]
Currently when built with Xcode 12.5, Secretive does not display secrets. There's no data loss and signing still functions fine, but it just looks empty. Rebuilding with Xcode 13 fixes. 
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/342665/125882677-caa96a0a-4789-486c-8150-9fa7c6af4eec.png">

`FB9338177`

**Comment by caraar12345** [comment]
Oh thank god it's a known thing 😄 
Was afraid I was going to have to generate more 😆 
Cheers for Secretive - it's a genuine life changer ❤️

**Comment by maxgoedjen** [comment]
I've published a [beta build of 2.1.1](https://github.com/maxgoedjen/secretive/releases/tag/v2.1.1_beta1) that fixes this. Fair warning, this release is compiled with a prerelease Xcode and may have other issues – but it does appear to address this issue. Hopefully Apple fixes the underlying issue in 12.0b4.

**Comment by maxgoedjen** [comment]
This release has been superseded by a [new beta build of 2.1.2](https://github.com/maxgoedjen/secretive/releases/tag/v2.1.2_beta1)

**Comment by maxgoedjen** [comment]
This appears to be fixed in Monterrey beta 5.
