### ISSUE TITLE
Support for Ed25519 type keys

### ISSUE THREAD

**Issue by Vascko** [maxgoedjen/secretive#232]
Hi folks,

I love this tool and was wondering if there are any plans to support Ed25519 keys in the future or even the option to specify the algorithm a user wants to use during secret creation?
From what I could find, OpenSSH has support for Ed25519 type keys since v6.5.

Kind regards

**Comment by maxgoedjen** [comment]
@Vascko OpenSSH does, and I'd love to support that, but AFAICT the Secure Enclave doesn't, at least for now (previously discussed here: https://github.com/maxgoedjen/secretive/issues/109). If that changes I'd definitely be interested in doing that!
