### ISSUE TITLE
New key did not show up in ssh agent

### ISSUE THREAD

**Issue by zacwest** [maxgoedjen/secretive#239]
I added a key, fingerprint like:

```
SHA256:MQrZUs2vGKhxftI…
```

I tried to connect to a server, with `-v` showing a list of:

```
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:hTDk1POG2lh8y+… agent
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:/hO0v/98rSCh3l… agent
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:bgNdGR893sUMaE… agent
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:rg2HqqWOg3F6Et… agent
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:uNKD0vduBWZrat… agent
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:+s1KXoiE+37I8s… agent
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:k/9T/Vrezblbd0… agent
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:atfGtJ+Fdrxt2s… agent
debug1: Will attempt key: ecdsa-sha2-nistp256 ECDSA SHA256:Jv3EUFp//bqBca… agent
```

I tried to `ssh-add -l` and it crashed:
[SecretAgent_2021-09-20-114613_Zacs-MacBook-Pro.crash.txt](https://github.com/maxgoedjen/secretive/files/7200093/SecretAgent_2021-09-20-114613_Zacs-MacBook-Pro.crash.txt)

Once the agent restarted, the new key was available.

**Comment by maxgoedjen** [comment]
Yeah I feel like I've occasionally run into this before. #214 should fix this but I haven't gotten around to implementing yet.

**Comment by maxgoedjen** [comment]
(I'm kinda 🤞we're gonna get some sort of Swift-distributed-actors-powered XPC replacement soonish, so I've been kinda leery of porting this to the existing stuff)
