### ISSUE TITLE
Create secret with "Authentication not required when Mac unlocked" doesn't prompt

### ISSUE THREAD

**Issue by ArisBee** [maxgoedjen/secretive#250]
Hello,

This application is terrific!! I really enjoy it and try to push everyone at my org to use it as we're all working on recent MacOS laptops. However the first option at secret creation (Authentication before each use) triggers some bugs with several automated applications interacting with GH repositories, the second option avoid these bugs but then users are never prompted for their password or Biometric which isn't compliant with some of our policies ...

Do you perhaps know if there is a way of modifying the [create function](https://github.com/maxgoedjen/secretive/blob/88b7ef82dabd78fb21318c854e43a3dfa0d2864d/SecretKit/SecureEnclave/SecureEnclaveStore.swift#L29-L65) to prompt for a password/biometric at least once a day to access the secret in the SecureEnclave's keychain? I thought perhaps by modifying the [kSecAttrAccessControl](https://developer.apple.com/documentation/security/ksecattraccesscontrol) key and another of the attribute? That may sounds noobish, but I've never touched a Swift codebase before and I find Apple's developer documentation rather obscure.

Please let me know if you have any idea and many thanks for this great interface! 😃

**Comment by maxgoedjen** [comment]
Hey @ArisBee – this is a pretty highly requested feature (https://github.com/maxgoedjen/secretive/issues/238) but as fa as I'm aware, there's not currently a way to set this up with the SEP (there's a few "validity window" type params, but they haven't worked with the SEP in my experimentation). I'd love to be wrong about this so I'll definitely add this if it turns out there is a way/if Apple adds support for that.

**Comment by ArisBee** [comment]
Hi @maxgoedjen , if you hear that Apple adds support for such a "validity window" and you have time to work on it, please let me know. I should be able to unlock some funds from our corporate Open Source program for your work.

**Comment by maxgoedjen** [comment]
Duping this out to #193, but I played around with this a little bit more today and _might_ have a path forward (although it has some security implications I need to consider and that I'll discuss in that thread).
