### ISSUE TITLE
Support Git 2.34 SSH Signatures

### ISSUE THREAD

**Issue by rawkode** [maxgoedjen/secretive#265]
It looks like Git 2.34 added support for signing commits with an SSH key, however I've been unable to get this to work with the Secretive ssh-agent.

It would be fantastic if this was possible :)

https://github.blog/2021-11-15-highlights-from-git-2-34/

**Comment by maxgoedjen** [comment]
Way ahead of ya 😉 #262
FWIW this does work already with Secretive (steps are listed in a very condensed format in that ticket) but GitHub currently doesn't recognize them.

**Comment by rawkode** [comment]
Awesome 😄 Thank you
