### ISSUE TITLE
Secretive agent flat out stopped working (Monterey 12.1, MBP14'21 M1)

### ISSUE THREAD

**Issue by rzwitserloot** [maxgoedjen/secretive#282]
Secretive the application runs fine and shows the keys, but doesn't appear to be doing anything - specifically, `ssh myserver` doesn't work anymore and I can't see anything at all about ssh even trying to use the agent when I run `ssh -vv`, but I don't know what that is supposed to look like if secretive IS working properly. I get no notifications.

It worked fine immediately before I upgraded to monterey 12.1, but I was also messing with zsh and installed oh-my-zsh and, naturally, the OS update also meant a reboot, so it's possible that the upgrade to 12.1 is a red herring here.

Things I've checked:
* `.zshrc` contains the SSH_AUTH_SOCK variable. `echo $SSH_AUTH_SOCK` shows this. If I `ls` this, it's there.
*  `ps auxww` shows that SecretAgent is running. 
* my .ssh contains the IdentityAgent line under `Host *`.
* ssh works fine; if I use plain old file-based keys (`ssh -i some_key_file`), that works fine.
* Secretive.app runs fine and shows my keys.

Things I'd like to know about:

* Does SecretAgent have any logs? Is there any app I can use to check specifically if it's 'working'? Right now all I know how to use is `ssh`, and `git`, but git uses ssh, I think, so that's still just the one tool.
* Can anyone tell me if their Secretive work on 12.1?
* If it does, can someone tell me if `ssh -vv` shows _anything at all_ about hitting that agent and using it? Presumably it will. A dump of what `ssh -vv` should look like may help me figure out what's going on here.
* Any further ideas about what I should do to fix this?

If there's any further information I can gather or anyone has a good idea on how to gather more information or stuff to try by all means of course.

Gracias, max, for an interesting project.

**Comment by maxgoedjen** [comment]
Hey @rzwitserloot 

> Does SecretAgent have any logs? Is there any app I can use to check specifically if it's 'working'? Right now all I know how to use is ssh, and git, but git uses ssh, I think, so that's still just the one tool.

Not in production builds, if you're comfortable opening it up in Xcode though, the agent is reasonably well-logged.

> Can anyone tell me if their Secretive work on 12.1?
Yep, I run it on 12.1 without issue personally.

> If it does, can someone tell me if ssh -vv shows anything at all about hitting that agent and using it? Presumably it will. A dump of what ssh -vv should look like may help me figure out what's going on here.
There's a (one v) log here you can check out, also on 12.1: https://github.com/maxgoedjen/secretive/issues/279. Basically what you're looking for is one of the keys you have locally being offered/accepted
```
debug1: Offering public key: /Users/admin/.ssh/pubkeys/homenet.pub ECDSA SHA256:KPM9xgCcDb6m6HIArb5btgMS5ruJr0cL4V0sG8ZnQlk explicit
debug1: Server accepts key: /Users/admin/.ssh/pubkeys/homenet.pub ECDSA SHA256:KPM9xgCcDb6m6HIArb5btgMS5ruJr0cL4V0sG8ZnQlk explicit
```

> Any further ideas about what I should do to fix this?
It sounds like you've got things set up correctly... If you haven't tried just killing the agent and letting it restart (it should automatically), give that a go. Occasionally it gets stuck, I haven't found the underlying issue there. If you're able to reproduce that state, I'd be curious to see what's happening there.

**Comment by rzwitserloot** [comment]
>  If you haven't tried just killing the agent and letting it restart (it should automatically), give that a go.

"Have you tried turning it off and on again", huh.

Yup, I should have known better and tried this. Apologies for not doing so - just `kill pid-of-SecretAgent` and that was all it took. Works fine again :)

Thanks for looking into it and doing me the kindness of at least leaving that embarrassingly obvious 'things to try' suggestion for last :)

**Comment by maxgoedjen** [comment]
😆 I've definitely run into it myself and gotten confused as hell so don't beat yourself up too bad over it. Tracking this freeze separately as #283 just so it doesn't fall off my radar agin.
