### ISSUE TITLE
[FR] Support using multiple storage mediums

### ISSUE THREAD

**Issue by catleeball** [maxgoedjen/secretive#287]
Sorry if this exists and I missed it! Couldn't find it in the UI or docs.

It would be nice if Secretive had a workflow for a machine with multiple storage mediums, e.g. the SEP plus some number of smartcards.

In my specific case, I set up Secretive using the SEP on my macbook, but I would also like to use Secretive and SecretAgent to store/access secrets on my Yubikey. It would be nice to use both during my regular workflow without switching tools or agents.

Thanks!

**Comment by maxgoedjen** [comment]
@catleeball it's a little hidden (and _mostly_ intended for Macs without SEPs) but this shoullllllllld just work out of the box. You'll need to do the configuration using the Smartcards themselves (using something like YubiKey Manager) and only certain types of keypairs are supported, but it should work.

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/342665/147624962-1a2f6b9b-2464-48b8-9144-be6072d3dfbf.png">
<img width="931" alt="image" src="https://user-images.githubusercontent.com/342665/147624919-7509b188-75b2-4861-b832-f5cd489fc689.png">

**Comment by catleeball** [comment]
Oops, my mistake! I realized since my new security key didn't have any credentials on it, it wasn't showing up in Secretive.

Now that I have some things on my key, I can see it in Secretive's UI. Thanks! :)

P.S. I saw https://github.com/maxgoedjen/secretive/issues/290 and just wanted to put in my two cents: Age is super cool and I would personally love to see plugin integration with it. 👍

**Comment by maxgoedjen** [comment]
All good! Thanks for confirming. 

Plug-in api definitely has the possibility of being cool, lots of trade offs to consider first though 😅
