### ISSUE TITLE
`ssh-copy-id` does not work

### ISSUE THREAD

**Issue by t123yh** [maxgoedjen/secretive#288]
The `ssh-copy-id` and `ssh-add -L` reports that no identity could be found from Secretive.

```
t123yh@t123yh-mbp ~/.ssh> echo $SSH_AUTH_SOCK
/private/tmp/com.apple.launchd.TLI6xF2JuN/Listeners
t123yh@t123yh-mbp ~/.ssh> ssh-add -L
The agent has no identities.
```

I would like to know if it's possible for this to be implemented in the agent?

**Comment by maxgoedjen** [comment]
@t123yh `ssh-add -L` definitely correctly lists my keys. That auth_sock looks pretty odd to me... is that what the setup flow gave you? It should look something like `/Users/max/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh`

**Comment by maxgoedjen** [comment]
FWIW `ssh-copy-id` seems to work fine (you have to paste the public key into a file, at least until I address #261) as well.

<img width="682" alt="image" src="https://user-images.githubusercontent.com/342665/147716982-e51bc30b-4924-44d8-8490-f8d2eabd6ca4.png">

**Comment by t123yh** [comment]
Hi Max,

Thanks for your reply! The `SSH_AUTH_SOCK` I'm currently using is indeed wrong. I followed instructions in [this page](https://superuser.com/questions/1120480/cant-change-ssh-auth-sock-with-launchctl-setenv) to link Secretive ssh socket to current SSH_AUTH_SOCK, and it works now.
