### ISSUE TITLE
For many reasons, I can’t fully switch to Secretive, but I like the approach it provides. Unfortunately, it doesn’t appear that the agent functionality provided by SecretAgent does not let me add externally stored keys like the standard agent does.

### ISSUE THREAD

**Issue by qygce8-juffIh-kubcom** [maxgoedjen/secretive#324]
For many reasons, I can’t fully switch to Secretive, but I like the approach it provides. Unfortunately, it doesn’t appear that the agent functionality provided by SecretAgent does not let me add externally stored keys like the standard agent does.

Ideally, I would be able to do:

```sh
$ ssh-add --apple-load-keychain
# May be new in Monterey
```

But I can’t even do:

```sh
$ ssh-add ~/.ssh/id_ed25519
Enter passphrase for /Users/halostatue/.ssh/id_ed25519:
Could not add identity "/Users/halostatue/.ssh/id_ed25519": agent refused operation
```

__Originally posted by @halostatue in https://github.com/maxgoedjen/secretive/issues/323__

**Comment by maxgoedjen** [comment]
Unfortunately for this purpose, as part of the design of the Secure Enclave, it's not possible to import or export keys, so ssh-add won't work (and isn't even implemented in the app).

**Comment by halostatue** [comment]
@maxgoedjen Please note that this appears to be a spam clone of my issue (#323).

**Comment by maxgoedjen** [comment]
@halostatue weird. Sorry about that, I'll crosspost.
