### ISSUE TITLE
Replace MD5 Fingerprint?

### ISSUE THREAD

**Issue by DestroyerXyz** [maxgoedjen/secretive#327]
Hi,
I don't know much about hashing and security but I have read that MD5 is now considered insecure so maybe you should replace MD5 in the app with something like BLAKE3 or SHA-3 (the shiny new hashing algorithms)? Or maybe just SHA-256 is enough.

**Comment by maxgoedjen** [comment]
Hey @DestroyerXyz - md5 is indeed cryptographically secure, but it's only use in Secretive is as a "fingerprint" (just for visual identification, basically) and not any cryptographic purposes where its insecurities would be a problem. We do support SHA256 fingerprints as well, but they're quite new for SSH - less than a year I think? So md5 fingerprints will probably be around until everyone switches at least. Thanks for the suggestion though :)
