### ISSUE TITLE
Document proper way to uninstall helper application

### ISSUE THREAD

**Issue by spkane** [maxgoedjen/secretive#336]
It would be great, if the README documented how to ensure that the helper application is uninstalled, when someone deletes the application.

**Comment by spkane** [comment]
Does simply uninstalling the application take care of the helper application, as well? My testing suggests yes, but honestly I was a bit surprised and it wasn't obvious.

**Comment by maxgoedjen** [comment]
Yep that's all it should take. The process probably will continue running until you quit it, but it doesn't move any files around on disk or anything.
