### ISSUE TITLE
Bring back longer unlock durations please?

### ISSUE THREAD

**Issue by taxilian** [maxgoedjen/secretive#345]
Hi, I recently updated to a newer nightly and was quite disappointed to find that the longest unlock duration is now 1h; 24h is a bit long, I admit, but couldn't we at least get some longer options? Honestly 8h would be ideal for me, but even 24h is fine as long as #332 pans out (and in my experience so far it does seem to re-lock when the system locks).

I tried to find an explanation of why 24h was removed but I couldn't find anything; I was all set to encourage all my coworkers to use it and then found my favorite feature had just become 10% as useful to me.

**Comment by taxilian** [comment]
I won't swear that it was working for a full 24h, but it definitely was
working for the afternoon =]

**Comment by maxgoedjen** [comment]
@taxilian alrighty then, I'll revert this. If you'd do me a favor – can you keep track of how long it seems to be working? I'm _pretty_ sure it won't work for 24h, but I'd definitely like to let it be whatever the practical limit of it is.

**Comment by taxilian** [comment]
I will do my best, however from my observations the limit seems to have been more due to other factors resetting it rather than time. For example:

* Unlocking it for one application does not seem to unlock it for others; e.g. if I use it in vscode terminal it's unlocked for other vscode instances, but not for operations from iterm
* If I leave my computer long enough for the computer to lock I have to unlock it again

I don't believe I've seen it lock again other than those two case, but I'll try to pay more attention.
