### ISSUE TITLE
Why not in the App Store?

### ISSUE THREAD

**Issue by jaydisc** [maxgoedjen/secretive#353]
Is there a knowable reason that this app isn't published in the App Store? Are releases at least notarised?

**Comment by maxgoedjen** [comment]
Releases are notarized. 

Basically 2 main reasons:
- I wanted a release process that allowed people to verify the final product was built with the source they can see.
- The Mac App Store (at least, compared to iOS) really isn't good enough to bother with IMO

Also I'm not 100% sure the agent etc etc would work properly in MAS.
