### ISSUE TITLE
Temporary unlock not working/prompting

### ISSUE THREAD

**Issue by maxgoedjen** [maxgoedjen/secretive#354]
I don't seem to get the second prompt. Here is a quick video

https://user-images.githubusercontent.com/1634878/154552841-538be174-f65a-4119-b59f-f792f3889c07.mov

__Originally posted by @zachberger in https://github.com/maxgoedjen/secretive/pull/252#issuecomment-1043315048__

**Comment by zachberger** [comment]
I just rebooted my computer and now this works. I think after updating the agent wasn't restarted. Perhaps the first launch of the app after it being updated should include a restart of the agent?

**Comment by maxgoedjen** [comment]
@zachberger that only makes it weirder 😂

The notifications are shown by the agent - if you were seeing the option to temporarily unlock that means the agent was updated... not sure what's going on there. I'll try and repro here, but let me know if it happens again.
