### ISSUE TITLE
public keys vanished after updating to macOS 12.3

### ISSUE THREAD

**Issue by ericlagergren** [maxgoedjen/secretive#367]
Is there a way to get them back?

Also, thank you for such a wonderful application.

**Comment by ericlagergren** [comment]
False alarm. I killed and restarted SecretAgent and it's back to normal.

**Comment by maxgoedjen** [comment]
Hey @ericlagergren - just to clarify, did the public key *files* on disk disappear or are they entirely gone in the main app?

If it's the former they should get recreated on agent relaunch. You can kill SecretAgent from Activity Monitor to do that.

**Comment by ericlagergren** [comment]
@maxgoedjen yes, sorry, the public key _files_ disappeared and they reappeared after killing and restarting SecretAgent.

It's odd that SecretAgent did not re-write the public keys to disk after my laptop restarted from the macOS upgrade, but I'm also fairly unfamiliar with macOS apps.

**Comment by maxgoedjen** [comment]
Phew, was scared it was a data loss bug for a sec 😌. 

Possible something just went weird during startup/upgrade... basically it should just do that on launch. I'll keep the ticket open, let me know if you run into it again. Thanks!

**Comment by schickling** [comment]
FYI I was facing the same issue. Restarting the agent did the trick for me as well. But I definitely got scared for a moment (until I found this issue).

**Comment by ericlagergren** [comment]
fwiw, just ran into this again after updating to 13.0.1 (22A400).
