### ISSUE TITLE
jrneef

### ISSUE THREAD

**Issue by AndroidKitKat** [maxgoedjen/secretive#381]

**Comment by AndroidKitKat** [comment]
Oops, I touched my Yubikey trying to set it up with Secretive. Apologies

**Comment by maxgoedjen** [comment]
😆 FYI you can disable that behavior if you don't use it https://support.yubico.com/hc/en-us/articles/360013714379-Accidentally-Triggering-OTP-Codes-with-Your-Nano-YubiKey
