### ISSUE TITLE
Issue with unlocking for a period time stops working

### ISSUE THREAD

**Issue by duchscherd** [maxgoedjen/secretive#384]
I was testing out the unlock feature for a period of time and it stopped working.  After poking around a bunch, I found what was causing the issue, at least, for me.

Everything worked the first ssh session.  Logged into the system and then use the pull down to set the time to keep things unlocked.  Responded to the authentication prompt for that and everything was good until it wasn't.

Testing a bunch of stuff, I found when I was clearing the notification, if I was not careful and missed the close button and ended up hitting the notification window, the key was re-locked and you could no longer use the unlock for a period of time for that key. If you selected unlock for a period of time, the notification would go away but you would not be prompted to approve it, and you would continue to be prompt to approve each ssh session.  Killing the agents would get things working again.

This looks to have selected 'Do Not Unlock" and re-locks that key.  Don't know if it is possible but it would be nice to add an the option to the list when unlocked for a period of time to have a leave unlocked as the default for the remaining time.

It does look like there is a bug that breaks this feature if "Do Not Unlock" is selected after you have unlocked the key for a period time.

**Comment by maxgoedjen** [comment]
@duchscherd great find! Turns out it's not actually re-locking it, but crashing the agent 👀 
<img width="1541" alt="image" src="https://user-images.githubusercontent.com/342665/172027228-3a9826a5-6f8d-445c-9c6c-d95ff543c687.png">

Basically I had thought that if I didn't attach a category to that, it wouldn't do anything. Easy enough fix though.
