### ISSUE TITLE
Feature Request: Log Of Usage in UI

### ISSUE THREAD

**Issue by adrianmace** [maxgoedjen/secretive#390]
👋

Extending on #389, I'd like to be able to see a log of key usage within the Secretive UI and perhaps even also what process used it.

**Comment by maxgoedjen** [comment]
@adrianmace thanks for the suggestion! I've got a ticket for this one already here: #56 

In short, I haven't done this one for two reasons:
1: Fairly complex feature, with a decent amount of bookkeeping/UI work needed. In line with my "you should be able to audit this codebase to make sure you trust it" guideline, I've been skeptical this is worth the added complexity.
2: The much bigger one, I'd be pretty concerned about maintaining the integrity of this log. While I mention a possible approach in that ticket (signing the log), it'd be fairly trivial for an attacker to roll back the log to a previous iteration to conceal activity. Basically the log is only worth how much you can trust it, and I don't have a great solution for that.
