### ISSUE TITLE
ssh with forwarded agent fails about 50% of the time

### ISSUE THREAD

**Issue by Roguelazer** [maxgoedjen/secretive#392]
Using secretive and SSH agent forwarding (`-A`), using SSH on the remote side (that is to say, running `ssh -A host1` then, from that session, running `ssh host2`) fails about 50% of the time with

```
sign_and_send_pubkey: signing failed: communication with agent failed
```

This never fails locally, so I assume it's something to do with the agent-forwarding protocol. This never happens when using regular ssh-agent, only when using Secretive.

This does not happen if running ssh under strace or with `ssh -vv` (both of which significantly slow down ssh; this makes me think that this is some kind of timing issue (maybe a problem when the SSH_AGENTC_REQUEST_IDENTITIES and SSH_AGENTC_SIGN_REQUEST commands are sent in very rapid sequence?).

This happens with multiple remote servers on different distros, running OpenSSH 8.0p1, 8.4p1, and 8.7p1

**Comment by espadolini** [comment]
Just hit this today when trying to use my Secretive key in a multipass VM running on localhost, so with very fast networking between the ssh client trying to use the key, the sshd/ssh pair forwarding the connection to the agent and the Secretive agent itself. Connections almost always (but not always) succeed with `ssh -vvvvv` but fail at no or lower verbosity.

**Comment by dfsnow** [comment]
Same issue here. This pretty much makes Secretive non-usable for me.
