### ISSUE TITLE
[Feature Request] Allow custom email for key generation

### ISSUE THREAD

**Issue by jidicula** [maxgoedjen/secretive#399]
Currently, secretive generates the email portion of an SSH key in the format of `keyname@secretive.hostname.local`. Could this last field in the key be instead generated according to an arbitrary email?

I don't quite like the idea of my keyname and hostname being publicly visible when using a Secretive key for [signing commits](https://github.com/orgs/community/discussions/7744), so configurability of what goes in the email field of a key pair would be fantastic.

**Comment by maxgoedjen** [comment]
FWIW the email at the string isn't actually tied to anything – you can just put whatever you want in there and it'll work fine (or just omit it entirely).

**Comment by maxgoedjen** [comment]
There have been a few requests over the years to customize what the default in Secretive is though, so I'm gonna dupe this out to one of those. My feeling so far has been that the complexity of the UI is probably not worth it given how frequent the requests come, but I'm always open to revisiting that if it becomes a more common request.

**Comment by maxgoedjen** [comment]
Duplicates #278

**Comment by jidicula** [comment]
Thanks, I had 1) not understood that the email comment in the key string isn't tied to anything and 2) not used the correct search keys when browsing for previous similar issues.

**Comment by maxgoedjen** [comment]
No worries, I didn't really know it myself until this project. Dupes like this are also always good for feeling out demand. 🙏
