### ISSUE TITLE
Add public key to ~/.ssh

### ISSUE THREAD

**Issue by asmeurer** [maxgoedjen/secretive#403]
It's a little confusing that the public key is buried in ~/Library somewhere. Is there a reason it isn't included in ~/.ssh/, at least as a symlink?

**Comment by maxgoedjen** [comment]
Yeah, it's because that path is within the sandbox secretive has access to.

**Comment by maxgoedjen** [comment]
Nothing that would prevent you from symlinking it though, if you were so inclined.

**Comment by asmeurer** [comment]
If Secretive can write to ~/.ssh/config during the setup shouldn't it also be able to write a symlink there?

**Comment by maxgoedjen** [comment]
This is actually a little bit of sleight of hand on Secretive's part - we're given write access to that specific file if you explicitly select it from the file dialog - but we can't access ~/.ssh in general
