### ISSUE TITLE
Git SSH signature not working

### ISSUE THREAD

**Issue by maxgoedjen** [maxgoedjen/secretive#404]
I'm on git version 2.37.2 and have the exact same two errors as @artis3n above with the `key::` inline format or the file location. I noticed that, with the latter, the `No such file or directory?` error message has the complete and accurate path except without the `.pub` extension (is it looking for a matching private key?).

`SSH_AUTH_SOCK` is set correctly and everything else about Secretive works well.

_Originally posted by @sean-public in https://github.com/maxgoedjen/secretive/issues/262#issuecomment-1227985957_
cc @artis3n

**Comment by maxgoedjen** [comment]
Just as a sanity check, can you please tell me what `echo $SSH_AUTH_SOCK` outputs for you?

**Comment by sean-public** [comment]
Sure thing, here's what it's set to currently:

```
echo $SSH_AUTH_SOCK

/var/folders/k2/0927yy_n5r78z_lh8jvwtr6w0000gn/T//ssh-dvuVi4epgRfd/agent.67556
```

**Comment by artis3n** [comment]
Ahh. @maxgoedjen when setting up Secretive I followed the "global" instructions and updated my `~/.ssh/config`. I didn't realize I had to also do the zsh / bash profile changes. Maybe UX improvement during that section of setup.

**Comment by maxgoedjen** [comment]
Yeah those options used to be pretty equivalent but the signature flow is picky.
