### ISSUE TITLE
Support for generating non-ecdsa (ed25519) keys

### ISSUE THREAD

**Issue by tddschn** [maxgoedjen/secretive#407]
Secretive has been working great for me.  
Recently I started working with Azure VM which [doesn't support ed25519 ssh keys](https://docs.microsoft.com/en-us/troubleshoot/azure/virtual-machines/ed25519-ssh-keys), and it seems that Secretive only generates ed25519 keys.

ed25519 keys are more shorter and more secure, but it would be great if I can generate other formats of keys with Secretive. :)

**Comment by maxgoedjen** [comment]
Unfortunately the Secure Enclave only supports generating ECDSA keys currently, but I'll probably add ed25519 key support of the SEP eventually does.
