### ISSUE TITLE
Show if a SSH key requires Authentication before each use or not

### ISSUE THREAD

**Issue by teunvink** [maxgoedjen/secretive#411]
After creating a key, there's no (obvious?) way to tell if that key requires authentication for every use or not. Some indicator to see that easily would be nice.

**Comment by maxgoedjen** [comment]
It hasn't made it into a public release yet, but this is actually implemented in `main` (and recently [nightly builds](https://github.com/maxgoedjen/secretive/actions/workflows/nightly.yml)) as of https://github.com/maxgoedjen/secretive/pull/357

<img width="1211" alt="image" src="https://user-images.githubusercontent.com/342665/193517685-5b48cb2c-d454-4b1c-b96b-b573c16df0d2.png">
