### ISSUE TITLE
Is it possible to change a key from requiring Touch ID to authentication not required when unlocked

### ISSUE THREAD

**Issue by nmcc1212** [maxgoedjen/secretive#414]
Is it possible to change a key from Requires Authentication (Biometrics or Password) before each use to Authentication notrequired when Mac is unlocked. From what i can see it can only be changed when creating the key

**Comment by maxgoedjen** [comment]
As far as I know, you're correct and it can only be changed during creation

**Comment by nmcc1212** [comment]
Ok thanks
