### ISSUE TITLE
How to backup or export the keys ?

### ISSUE THREAD

**Issue by cbrassel** [maxgoedjen/secretive#423]
Hello,

I'm just testing Secretive and I like it but is there any way to make some backup of the keys ? or an export of the keys ?
or at least a list of files to backup ?

ideally a backup/restore to/from an Yubikey will be great !

A thank's for the nice job !
Regard's
Claude

**Comment by aisamu** [comment]
IIUC, this is not possible (and potentially a security "feature" of the Secure Enclave)

From the FAQ: https://github.com/maxgoedjen/secretive/blob/main/FAQ.md#how-do-i-import-my-current-ssh-keys-or-export-my-secretive-keys

**Comment by footlooseboss** [comment]
README.md

> If you store your keys in the Secure Enclave, it's impossible to export them, by design.

**Comment by cbrassel** [comment]
Yes I have read this .. but I just asking to be sure .. I don't like not having a backup of something so important, but I can understand why it is like this.

Regard's
Claude

**Comment by krystofbe** [comment]
Yes, I would not use this for production access when there is no possibilty of saving the keys somewhere save.
