### ISSUE TITLE
Change key authentification method after creation

### ISSUE THREAD

**Issue by cbrassel** [maxgoedjen/secretive#424]
Is it feasible to edit the authentification behavior of a key after creation ?

Going from biometric to none and vice versa ?

Regard's
Claude

**Comment by sandstrom** [comment]
Maybe some of these TODO issues could be moved to discussion, to keep the backlog count down.

https://github.com/maxgoedjen/secretive/discussions/categories/ideas

1 person wishing something, is usually not a strong enough signal to warrant building it.

Just a thought. It's easy for open-source projects to be overwhelmed with wishes.

**Comment by maxgoedjen** [comment]
@cbrassel to my knowledge this is not possible currently.

**Comment by cbrassel** [comment]
ok, thank you for the reply.

Have a nice day !

By the way the new release look's great !
Regard's
Claude
