### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by QuinnyPig** [maxgoedjen/secretive#431]
Didn't see anywhere else to put this feedback: I just want to say that Secretive has absolutely changed my security posture for the better. Thanks for building it; open source maintainership is a thankless job.

**Comment by maxgoedjen** [comment]
Hey @QuinnyPig, thanks for taking the time to write this. Like most things I work on, I mostly made this for myself, but it always warms my heart a bit to hear that I'm not alone, and other people appreciate the effort. Extra appreciate your sponsorship 🙏❤️

Be on the lookout for an update in the next week or two, lots of cool nice little stuff landing in this one, and some awesome community contributions, which I'm extra excited about!


Thanks again, and happy holidays 🥳!
