### ISSUE TITLE
Proposal: Let users select a secret for Git SSH signing

### ISSUE THREAD

**Issue by gl-njanz** [maxgoedjen/secretive#442]
I'd like to propose a setting that lets user set their preferred Git `user.signingkey`.\
Perhaps as a button in `SecretListItemView` context menu?

**Comment by slimm609** [comment]
This should be set on a per repo list
```shell
git config user.signingKey $pubkey/path/key.pub
```

**Comment by maxgoedjen** [comment]
Yeah I'm inclined to agree with @slimm609 here – basically the posture we've taken so far is "let the requester specify what key they want via their native config mechanisms" for everything. If there's some reason that that approach specifically wouldn't work for your use case, please reopen this, I'd be interested in hearing about it.
