### ISSUE TITLE
Instructions for setting up Xcode

### ISSUE THREAD

**Issue by pahnev** [maxgoedjen/secretive#448]
There are couple of apps listed in https://github.com/maxgoedjen/secretive/blob/main/APP_CONFIG.md.
Would it be possible to add Xcode there? Is it even possible to setup with secretive?

Having the `IdentityAgent` in the `.ssh/config` doesn't seem to satisfy Xcode:
![Screenshot 2023-02-15 at 7 20 01](https://user-images.githubusercontent.com/2078494/218940147-84c1e8ee-e18a-4a51-97c5-95fe5caf5148.png)

**Comment by maxgoedjen** [comment]
Yeah Xcode is unfortunately poorly behaved – it doesn't interact with an agent, it tries to load keys (including private keys) directly. I'm not aware of any workarounds but I'd love to be wrong.
