### ISSUE TITLE
Secrets disappeared suddenly

### ISSUE THREAD

**Issue by clem-hertling** [maxgoedjen/secretive#467]
Hey,

today, after no particular activity, while doing a git ssh-signed commit, git complained I don't have an SSH key. I was surprised and took a look at Secretive and sure enough, no ssh keys.

this machine hadn't been rebooted in 2 weeks and worked before today, I git pushed less than 24 hours before this happened and didn't do anything between then and now. I have tried rebooting (twice), which didn't fix the problem, I killed all processes and that didn't do it, and I also tried making a new dummy key, and that *worked*, it did create the key, but it did not bring the old keys back.

I am... in a tough spot, without my ssh key I can't sign commits or push them. Thanks for your help

**Comment by maxgoedjen** [comment]
@clem-hertling hey, sorry to hear that – we've had a few reports of similar issues but none I'm aware of that haven't been fixed by a reboot. Can you do that a go and report back please?

**Comment by maxgoedjen** [comment]
This is the running ticket for other people who have had similar issues where reboot fixed: https://github.com/maxgoedjen/secretive/issues/378 but I see you did reboot in your message and can't see them still.

Just to verify: you haven't reinstalled Secretive recently or anything?

**Comment by clem-hertling** [comment]
No reinstall, no upgrade before the problem. I did upgrade *after* through brew and it also didn't fix the problem, so I'm thinking this is probably a different thing from #378. It *could* be a problem with the SEP? it did ask me to input my CardDAV account password again, though not any other accounts, so...

**Comment by maxgoedjen** [comment]
Yeah that's a little suspect. My suspicion would be more of a general keychain issue than a SEP specific one though if that's the case. 

To start with can you try downloading the version that's on the release page in GitHub? I doubt that's it but it'd be good to rule it out.

**Comment by clem-hertling** [comment]
that would also make sense, yeah.

just installed the github release, still only showing the dummy key I created after the problem and not the previous one

**Comment by clem-hertling** [comment]
update: it is asking me to log into all of my accounts again, so I guess everything on the machine lost their secrets, huh

**Comment by maxgoedjen** [comment]
Yeah it sounds like your keychain might have just blown up somehow, that sucks :/ 

Not sure there's a ton I can do to help beyond suggesting googling around for keychain repair, or using a backup if you've got one. 

Good luck, hope you're able to fix it 🤞🤞

**Comment by clem-hertling** [comment]
well, I wasn't able to recover the keychain, but it seems clear that this problem is not in secretive. Thanks for your work, I'll just eat my loss and set up new secrets
