### ISSUE TITLE
Set up strings catalog

### ISSUE THREAD

**Issue by maxgoedjen** [maxgoedjen/secretive#470]
https://developer.apple.com/documentation/Xcode/localizing-and-varying-text-with-a-string-catalog

**Comment by mgwalker** [comment]
Max, how are people supposed to contribute to your open source project if you don't describe your issues. C'mon. :trollface:

**Comment by maxgoedjen** [comment]
@mgwalker updated the ticket with a link, jeez. Government employees these days.
