### ISSUE TITLE
VSCode frequently prompting signing request

### ISSUE THREAD

**Issue by chasen-bettinger** [maxgoedjen/secretive#473]
Every five minutes or so, I'm getting this pop-up from `SecretAgent` asking me to authenticate a signing request. 

<img width="253" alt="Screenshot 2023-07-13 at 12 09 34" src="https://github.com/maxgoedjen/secretive/assets/24480592/0e105033-6f3c-4466-9665-0910e501b953">

I know I haven't provided much detail here, frankly I'm not aware how to debug and provide information for this sort of issue. Any guidance or direction to help me getting past this?

**Comment by maxgoedjen** [comment]
If you’re using some git integration in VSC, it’s probably just checking the remote for new commits every 5m. I’d recommend using a non-authentication-required key for that.

**Comment by chasen-bettinger** [comment]
@maxgoedjen I had the same hunch and your suggestion is the one I followed. Future readers, I advise you using a non-authentication-required key for SSH authentication between you and your SCM!
