### ISSUE TITLE
Unnotarized developer ID

### ISSUE THREAD

**Issue by parasaito** [maxgoedjen/secretive#488]
Gatekeeper wouldn't let me run it, kindly notarize app. This might also tie into another issue requesting to make Secretive available on App store for a fee.

<img width="736" alt="image" src="https://github.com/maxgoedjen/secretive/assets/97852663/466daaed-d2df-46f3-a1d8-1f20f6f4a035">

**Comment by maxgoedjen** [comment]
Are you sure? I don't staple a notarization ticket to it, but the app itself _is_ notarized. macOS should transparently download the notarization ticket on first launch, did you have an internet connection when this screenshot was taken?

<img width="1212" alt="image" src="https://github.com/maxgoedjen/secretive/assets/342665/eb852539-f269-4f13-855f-15593907a27e">
<img width="1212" alt="image" src="https://github.com/maxgoedjen/secretive/assets/342665/6aa93f9e-5dbb-4913-8c2d-b42e55a0b940">

**Comment by parasaito** [comment]
@maxgoedjen Sorry. There might have been a small window of no internet connection. It works fine as I checked today.

**Comment by maxgoedjen** [comment]
Appreciate the confirmation, thanks!
