### ISSUE TITLE
Text problems with pop-up windows

### ISSUE THREAD

**Issue by GravityRyu** [maxgoedjen/secretive#509]
Click on the Agent status button in the upper left corner, in which the redundant paging symbols are displayed
secretive Version: 2.4.0

![截屏2024-01-13 19 30 17](https://github.com/maxgoedjen/secretive/assets/149242398/823a8b86-ec59-4640-bfca-fd78f25487f6)

**Comment by maxgoedjen** [comment]
This should be fixed in https://github.com/maxgoedjen/secretive/pull/505 – I just got a little sloppy when I was pulling out strings 🤦.
