### ISSUE TITLE
Update notifications for 2.4 in 2.4

### ISSUE THREAD

**Issue by maia-s** [maxgoedjen/secretive#513]
I keep getting notifications about the 2.4 update being available, despite already having installed the update. I installed and updated secretive via homebrew.

**Comment by maxgoedjen** [comment]
@maia-s 2.4.1 is the current latest release, but looks as through it hasn't quite made its way to homebrew yet.

**Comment by maia-s** [comment]
The update notification says 2.4.0. Also, there's no 2.4.1 release here on github and no tag for it either.

**Comment by maxgoedjen** [comment]
@maia-s you're right, my memory is playing tricks on me. I'd been planning on doing it but hadn't yet, my bad.

Let me take a look and see why that's happening, though, that's weird. Do you see the update prompt in the main Secretive.app too? If it's only notifications, my suspicion would be you've got an old version of the agent running – can you please kill it in activity manager?

**Comment by maxgoedjen** [comment]
>  I tried killing the agent in the activity manager, but it wouldn't go away

You almost certainly actually killed it successfully, it just relaunches automatically. It's kinda hard to tell but you should be able to see the PIDs change in that column in Activity Monitor.

Generally you shouldn't need to restart the agent – it should attempt to kill the agent and restart it on launch of the new main app, but it's not perfect. Definitely please let me know if you keep getting notifications.

**Comment by maia-s** [comment]
I see. Thank you!

**Comment by maxgoedjen** [comment]
No worries! I'm gonna close this out for now but if you keep seeing the notifications please reopen!
