### ISSUE TITLE
[Feature/Bug] Yubikey not shown on macOS WITH secure enclave

### ISSUE THREAD

**Issue by MrXermon** [maxgoedjen/secretive#539]
I am running 2.4.1 on a MacBook Pro with a Apple M1 Pro running macOS 14.2.1 (23C71). I am currently using a Yubikey containing my SSH key which I use via "gpg-agent". Is there any chance to include support for Yubikeys on Macs with Secure Enclave support, too? This would make the migration from Yubikey to Secure Enclave more easier.

**Comment by maxgoedjen** [comment]
@MrXermon are you sure you have the YubiKey configured in a way Secretive can work with? It definitely should allow you to use both at once, I can do that here:
<img width="1108" alt="image" src="https://github.com/maxgoedjen/secretive/assets/342665/fe0723a5-2262-4582-98be-e272e5e76479">

Without knowing the details, my suspicion is you have the YubiKey set up with a format that Secretive isn't compatible with (Secretive currently only supports elliptic curve keys).

**Comment by MrXermon** [comment]
@maxgoedjen You are correct... It's a RSA-key and therefore not supported.
