### ISSUE TITLE
Investigate GPG support

### ISSUE THREAD

**Issue by maxgoedjen** [maxgoedjen/secretive#63]
https://www.gnupg.org/documentation/manuals/gnupg/Agent-PKSIGN.html#Agent-PKSIGN
Pose as generic SC with `scdaemon-program` config?

**Comment by maxgoedjen** [comment]
I'd definitely still be interested in adding this but definitely still pretty intimidated by that spec compared to the SSH one. If anyone's got any "simplified" reference implementations, feel free to paste them here :) (bearing in mind that like the SSH functionality, we really don't need to implement the full GPG suite – basically just key listing + signing + probably validation?)

**Comment by maxgoedjen** [comment]
Potential bummer of an issue with this: GitHub (and I'd imagine, many others) don't really seem to have the concept of "prematurely expiring" a key – eg if you were in this flow (which I personally am, at least)
1: Had a preexisting GPG identity that I've been signing commits with
2: Created a Secretive-backed GPG signing identity at some point after that
There'd be no way to "invalidate" that original key, without invalidating all of the signatures you've made on GitHub prior to that. This also makes migration a problem, since there basically is no migrating key material from one Secretive instance to another. Basically you'd have to leave your old key registered to your account even though you're no longer using it.

**Comment by maxgoedjen** [comment]
So basically I'd been thinking I needed to do a partial OpenPGP implementation to get this working for Git signing but that might not actually be necessary – git's interface with it seems to just be text based, so this may not be too bad actually...

Still have some concerns about migration/key lifetimes though.

**Comment by maxgoedjen** [comment]
[also, debating implementing an agent vs just like a whole-hog `gpg.program` replacement for git... Installing GnuPG on M1 was a bit of a pain so I'm debating on that one]

**Comment by maxgoedjen** [comment]
So basically, having researched it a bit, looks like if we  have secretive pose as a gpg-compatible program, that'll work, but obviously you won't be able to use your regular-gpg-stored keys anymore if you've set whatever program (presumably git) to consult secretive instead.
Alternatively, it looks like there's a smart card-backed agent we can tell the user's builtin gpg app to talk to, but the user will have to input the public keys manually into gpg before gpg will try and use them. I MIGHT be able to automate this (not sure yet) but that's a huge bummer if the user has to do it manually. It feels like the "right" way overall but there's two big steps to set that up (initial GPG setup + ingesting public keys). Not really sure how similar the two protocols are, they're both basically just text based, it might be feasible to support both.

**Comment by obra** [comment]
It’s worth looking at how krypt.co does this.  Their set up flow is incredibly smooth

**Comment by maxgoedjen** [comment]
@obra do they do GPG signing? I thought they were only WebAuthn, but I'm not super familiar with them.

**Comment by maxgoedjen** [comment]
Looks like they do... didn't know that, neat I'll have to check it out 🙏

**Comment by maxgoedjen** [comment]
Looks like they do what I described above (basically posing as a gpg program). Good to know it's not a super-out-there idea ;P
Still investigating before I decide if this is the way to go or not, but a good point of ref thanks!

**Comment by schickling** [comment]
@maxgoedjen is there any news about GPG support coming to secretive? GPG is so painful to work with so this would be a game changer! 🚀

**Comment by maxgoedjen** [comment]
@schickling at the moment I'm kind of waiting to see what comes of https://github.com/isaacs/github/issues/1099

Currently I don't think there's a ton of benefit to doing something like this with the SEP – the tradeoffs of what happens when you switch machines is pretty rough. If GitHub adds support for a "retired, but not invalidated" signature setup, I'll revisit this.

**Comment by Manouchehri** [comment]
> the tradeoffs of what happens when you switch machines is pretty rough

If we could only have a _subkey_ in Secretive, that would be awesome.

https://gnupg.org/howtos/card-howto/en/ch05s02.html

**Comment by maxgoedjen** [comment]
@Manouchehri a cool idea, but I'm not sure one that'd work with the design of the Secure Enclave – I _think_ since the subway is derived from the primary key, you'd need to generate it and then import it into the SEP, which it doesn't support (it can only generate keys internally, and doesn't support import/export). Additionally you'd have the problem that the primary key would be stored insecurely _somewhere_.

**Comment by maxgoedjen** [comment]
This is going to be obsoleted by #262. All of the concerns I have around https://github.com/isaacs/github/issues/1099 are still present, although this is so little work dev-side IMO it makes sense to support it with a warning about signature verification.

If anyone has any non-git-signature based uses of GPG in mind, I'm open to hearing them, thought this was kinda the driving factor for me personally.

**Comment by schickling** [comment]
My primary use case of GPG is https://github.com/AGWA/git-crypt

Do you see a way to support it as well? 

I also occasionally use the `gpg` CLI directly.

**Comment by maxgoedjen** [comment]
@schickling I'm pretty uncomfortable with Secretive being used for that type of encryption work anyway to be perfectly honest - with no meaningful way to back up keys it's just a matter of time before a data loss event happens.

**Comment by Stanpol** [comment]
There is a use case of non-git-signature based GPG encryption for a quite popular cli password manager [pass](https://www.passwordstore.org/) or it's go re-implementation [gopass](https://github.com/gopasspw/gopass). These password managers are using GPG for password encryption.

To address your issue that:
> with no meaningful way to back up keys it's just a matter of time before a data loss event happens.

There is a way to encrypt anything with 2 keys – [encryption with multiple keys](https://stackoverflow.com/a/597200). This way it is possible to have a second backup key which should be stored separately.

Maybe to simplify the start it is possible to implement an encryption of a GPG passphrase of a user key using Secretive private key in a Secure Enclave? 

- So a _secret password_ is encrypted with a user gpg key, the private user key has a passphrase selected by user.
- This passphrase for the user key is encrypted using another key pair stored by Secretive in a Secure Enclave. 
- Anytime user wants to decrypt something, instead of typing the passphrase a private key is fetched from the Secure Enclave, passphrase is decrypted and used where needed to decrypt a _secret password_. 

I believe such support can be done via custom `pinentry` program which is called every time for to enter a passphrase. There is already a small solution [pinentry-touchid](https://github.com/jorgelbg/pinentry-touchid), however it is not using Security Enclave.

**Comment by maxgoedjen** [comment]
@Stanpol I think it's pretty unlikely that I'll implement GPG specific support at this point, but I'm not necessarily ruling out something like support for age (https://github.com/maxgoedjen/secretive/issues/290), which would be a similar end result.

**Comment by asmeurer** [comment]
GitHub seems to have improved its support for revoked GPG signatures https://github.blog/changelog/2022-05-31-improved-verification-of-historic-git-commit-signatures/

**Comment by sneak** [comment]
My use case for something like this would be primarily for encryption, not signing.  I have several macs and several yubikeys and being able to gpg encrypt to all of them at once would be very helpful.

While the signing use case is probably the most popular one, general GPG support has more applications than that.
