### ISSUE TITLE
Add warning if app is not in /Applications

### ISSUE THREAD

**Issue by maxgoedjen** [maxgoedjen/secretive#77]
Apparently causes some issues with launch agent

**Comment by jnsdrtlf** [comment]
Just had this issue. I forgot to move `Secretive.app` into the `/Applications` folder. Thus, the agent could not be started. Maybe just add a step to the "Setup Helper App" view (where you are instructed to install the helper app) stating that you are required to move the application into `/Applications`.

I don't think you'll have to implement checks for this or the functionality to move the app automatically. Just a small little notice should be enough ;)
