### ISSUE TITLE
Deploy to Homebrew Cask?

### ISSUE THREAD

**Issue by chriscn** [maxgoedjen/secretive#93]
Would we be able to deploy this to Homebrew Cask?
If the releases get automatically made, that could work?

**Comment by chriscn** [comment]
https://github.com/Homebrew/homebrew-cask/pull/84036 
Let us hope they accept it.

**Comment by chriscn** [comment]
They've deployed it. So you should be able to install it by running `brew cask install secretive`

**Comment by maxgoedjen** [comment]
@chriscn thanks for setting it up! Long term I’d like to get it built into the CI process, but this is awesome to have in the meantime. 🙏
