### ISSUE TITLE
Change helper app button name

### ISSUE THREAD

**Issue by shanemikel** [maxgoedjen/secretive#94]
The helper app has two automated steps:
1. Install
2. Added

The button names don't change after the steps are complete.  I propose changing (2) to "Add."

**Comment by maxgoedjen** [comment]
@shanemikel I've named 2 "Added" as an indication that the user should click it after they've added the key (ie, Secretive doesn't do it automatically – the user has to do it themselves and confirm). I'm not sure "Add" is the right solution (feels like it implies that Secretive will do it for you IMO) but I'm open to alternative wording.

**Comment by shanemikel** [comment]
Do you mean after installing the helper app or after configuring the auth socket environment variable?  It doesn’t make sense to me that this is after adding a key, as it’s the first thing I saw.

**Comment by shanemikel** [comment]
What does this button do?  Reload the Shell environment to source the added variable?

**Comment by maxgoedjen** [comment]
@shanemikel the intent is for the user to indicate that they've added it their shell rc – the button itself doesn't do anything beyond act as a confirmation. There's nothing for us to source, since that's sort of on the "other end" of the connection – we don't know what terminal session they're using, etc.

**Comment by shanemikel** [comment]
How does secretive confirm the shell variable was added?  If it doesn’t do anything I would suggest removal.  If it tests the variable update maybe it could be called “Check variable” or something more indicative of the function

**Comment by maxgoedjen** [comment]
@shanemikel just to followup here: Secretive really _doesn't_ know this (both because I don't know what shell you're using, and because of sandboxing restrictions which prevent me from reading the config).

**Comment by maxgoedjen** [comment]
I've considerably improved this flow in the Big Sur update (#128).
