### ISSUE TITLE
Secretive keys in AWS

### ISSUE THREAD

**Issue by shanemikel** [maxgoedjen/secretive#95]
I've attempted to import secretive generated keys into AWS through the AWS management console.  It gives the message "Not valid OpenSSH public key format."

I'm not sure if the format is the problem, or if AWS doesn't support this type of key.  Usually I use RSA keys.  Is it possible to support the RSA format, or is ecdsa-sha2-nistp256 the only possible format with the Secure Enclave?

**Comment by maxgoedjen** [comment]
@shanemikel yeah unfortunately the Secure Enclave does not support RSA keys. Without more information on the failure in AWS it's a bit hard to say if it's "something about Amazon's validation of OpenSSH public keys is violating an assumption that Secretive makes" or "AWS just doesn't support ECDSA keys." (Secretive does nominally support other key formats, but only if you're storing them on Smart Card like a YubiKey (and even then I haven't bothered to support RSA, just other variants of ECDSA-SHA2)

**Comment by shanemikel** [comment]
It looks like AWS only supports RSA keys, and the error message is simply confusing.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-key-pairs.html

**Comment by shanemikel** [comment]
I wonder is there a secure way to encrypt an on-disk RSA Key with a Secure Enclave asymmetric Key?

**Comment by maxgoedjen** [comment]
Unfortunately no, the secure enclave only supports 256 bit elliptic curve keys. The smart card store could plausibly support this, but I haven't bothered implementing it yet due to lack of requests.
