### ISSUE TITLE
iTerm2 integration

### ISSUE THREAD

**Issue by gnachman** [maxgoedjen/secretive#98]
Have you considered exposing an API of some sort? I’d love to integrate with iTerm2’s password manager.

**Comment by maxgoedjen** [comment]
What kind of thing API did you have in mind?

**Comment by maxgoedjen** [comment]
<img width="696" alt="Screen Shot 2020-06-27 at 6 48 39 PM" src="https://user-images.githubusercontent.com/342665/85935537-dc665f80-b8a6-11ea-9120-e8011e47c61e.png">
It does work fine with iTerm 2 in general already, but I'm curious what you had in mind in terms of password manager integration.

**Comment by elmcrest** [comment]
Sync with 1Password ftw! 👯 😍 🤣

**Comment by gnachman** [comment]
This is the password manager I had in mind:

![image](https://user-images.githubusercontent.com/427546/85971150-38051b80-b981-11ea-8df8-59f42f015796.png)

Currently iTerm2 stores passwords in the system keychain. It would be much nicer to store them in a secure enclave. I'm not quite sure what the best way to accomplish that would be. One way to do it would be to have a Secretive framework that apps like iTerm2 could link in to provide CRUD operations on passwords in the secure enclave. Another option would be to expose some kind of IPC-based API, although I suspect that would have too many security issues to be practical.

**Comment by maxgoedjen** [comment]
Ah, yeah, the Secure Enclave's security design unfortunately makes this impossible. The current (public) API for it only supports storage of elliptic curve keys, not arbitrary data. The general security model also does not allow import/export of data of any sort (it will perform cryptographic operations on the user's behalf, but there's no way for it to actually take in a password/reveal it later. I think the keychain API you have currently is probably the best route to go :)

**Comment by maxgoedjen** [comment]
(I _DO_ seem to recall reading somewhere that Big Sur adds support for iOS-style password manager support though, but I'm having trouble finding a link for that so I might be wrong. If that is the case, as a diehard 1Password fan I _would_ love to see iTerm integrated with that 😉).

**Comment by gnachman** [comment]
That makes sense. Thanks for the explanation :) I'll give 1Password a go when I've got some free time.
